stages:
- name: Build
  steps:
  - runScriptConfig:
      image: 10.10.15.51/maven:3-jdk-7
      shellScript: mvn clean install
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34742
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 40
notification: {}
